ALTER TABLE chat_messages
  ADD COLUMN IF NOT EXISTS retention_seq BIGINT GENERATED BY DEFAULT AS IDENTITY;

CREATE INDEX IF NOT EXISTS idx_chat_messages_room_retention
  ON chat_messages(room_id, retention_seq DESC);
